### ISSUE TITLE
using AUParameterEvent::rampDurationSampleFrames with generated soul code

### ISSUE THREAD

**Issue by wtholliday** [soul-lang/SOUL#36]
I'm on macOS/iOS. An `AUParameterEvent` (see https://developer.apple.com/documentation/audiotoolbox/auparameterevent) has `rampDurationSampleFrames`. The soul-generated code's `ParameterProperties` only has `void setValue (float f)`.

**How can I accomplish this sort of ramping of parameters?**

I could run the soul code one sample at a time, ramping my own parameters, but that seems inefficient, plus it seems soul does its own ramping.

Thanks!

**Comment by julianstorer** [comment]
Well, if you declare the input as a stream rather than an event, then you'll see a function generated with a name like "setNextInputStreamSparseFrames_xyz" which lets you set a target value and ramp length for it.

BTW github "issues" are for bug-reports, not questions, and it's a bit of a clunky way to get help from us! We'd be happy to chat directly on the juce forum, or theaudioprogrammer discord channel, or just by email. We also have a soul slack group that we could add you to if you want to be in the loop on discussions
